openapi: 3.0.0
info:
  title: Crop API
  description: API for managing crops
  version: 1.0.0

tags:
  - name: crop
    description: CRUD operations for crop

paths:
  /api/v1/{toolID}/realm/{realmId}/user/{userId}/pesticides:
    post:
      tags:
        - pesticide
      summary: Add a new pesticide
      operationId: addPesticide
      parameters:
        - name: realmId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: integer
        - name: toolID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pesticide"
      responses:
        '200':
          description: Pesticide Added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pesticide"

  /api/v1/{toolID}/realm/{realmId}/user/{userId}/pesticides/{id}:
    parameters:
      - name: realmId
        in: path
        required: true
        schema:
          type: string
      - name: userId
        in: path
        required: true
        schema:
          type: integer
      - name: toolID
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - pesticide
      summary: Get a specific pesticide by ID
      operationId: getPesticideById
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pesticide"

    put:
      tags:
        - pesticide
      summary: Update a specific pesticide by ID
      operationId: updatePesticideById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pesticide"
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pesticide"

    delete:
      tags:
        - pesticide
      summary: Delete a specific pesticide by ID
      operationId: deletePesticideById
      responses:
        '204':
          description: Deleted Successfully

components:
  schemas:
    Pesticide:
      type: object
      x-class-extra-annotation: |-
        @jakarta.persistence.Entity
        @jakarta.persistence.Table(
            name = "pesticide"
          )
      properties:
        id:
          type: integer
          x-field-extra-annotation: |-
            @jakarta.persistence.Id
            @jakarta.persistence.GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
          description: Autogenerated primary key
          x-id-attribute: true
        createdBy:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedBy:
          type: integer
        updatedAt:
          type: string
          format: date-time
        createdByToolId:
          type: string
        updatedByToolId:
          type: string
        name:
          type: string
        chemicalComposition:
          type: string
        dosagePerAcre:
          type: string
        applicationMethod:
          type: string
        spectrum:
          type: string
        effectDuration:
          type: string
        applicationFrequency:
          type: string
        specialRemarks:
          type: string
        extraDescription:
          type: string
        costOfSingleDosage:
          type: integer
        benefits:
          type: string
        img1:
          type: string
        hashId:
          type: string
        brand:
          type: string
        form:
          type: string
        pesticideType:
          type: string
        price:
          type: integer
        dosagePerLitre:
          type: string
        quantity:
          type: string
        compatibility:
          type: string
        pesticideTypeId:
          type: integer
        urlStr:
          type: string
        versionId:
          type: integer
        is_deleted:
          type: boolean
          default: false
      required:
        - name