openapi: 3.0.0
info:
  title: Fertilizer API
  description: API for managing fertilizers
  version: 1.0.0

tags:
  - name: fertilizer
    description: CRUD operations for fertilizer

paths:
  /api/v1/{toolID}/realm/{realmId}/user/{userId}/fertilizers:
    post:
      tags:
        - fertilizer
      summary: Add a new fertilizer
      operationId: addFertilizer
      parameters:
        - name: realmId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: integer
        - name: toolID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fertilizer"
      responses:
        '200':
          description: Fertilizer Added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fertilizer"

  /api/v1/{toolID}/realm/{realmId}/user/{userId}/fertilizers/{id}:
    parameters:
      - name: realmId
        in: path
        required: true
        schema:
          type: string
      - name: userId
        in: path
        required: true
        schema:
          type: integer
      - name: toolID
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - fertilizer
      summary: Get a specific fertilizer by ID
      operationId: getFertilizerById
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fertilizer"

    put:
      tags:
        - fertilizer
      summary: Update a specific fertilizer by ID
      operationId: updateFertilizerById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Fertilizer"
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Fertilizer"

    delete:
      tags:
        - fertilizer
      summary: Delete a specific fertilizer by ID
      operationId: deleteFertilizerById
      responses:
        '204':
          description: Deleted Successfully

components:
  schemas:
    Fertilizer:
      type: object
      x-class-extra-annotation: |-
        @jakarta.persistence.Entity
        @jakarta.persistence.Table(
            name = "fertilizer"
          )
      properties:
        id:
          type: integer
          x-field-extra-annotation: |-
            @jakarta.persistence.Id
            @jakarta.persistence.GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
          description: Autogenerated primary key
          x-id-attribute: true
        createdBy:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedBy:
          type: integer
        updatedAt:
          type: string
          format: date-time
        createdByToolId:
          type: string
        updatedByToolId:
          type: string
        name:
          type: string
        is_deleted:
          type: boolean
          default: false
      required:
        - name
