openapi: 3.0.0
info:
  title: Seed API
  description: API for managing seeds
  version: 1.0.0

tags:
  - name: seed
    description: CRUD operations for seed

paths:
  /api/v1/{toolID}/realm/{realmId}/user/{userId}/seeds:
    post:
      tags:
        - seed
      summary: Add a new seed
      operationId: addSeed
      parameters:
        - name: realmId
          in: path
          required: true
          schema:
            type: string
        - name: userId
          in: path
          required: true
          schema:
            type: integer
        - name: toolID
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Seed"
      responses:
        '200':
          description: Seed Added
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seed"

  /api/v1/{toolID}/realm/{realmId}/user/{userId}/seeds/{id}:
    parameters:
      - name: realmId
        in: path
        required: true
        schema:
          type: string
      - name: userId
        in: path
        required: true
        schema:
          type: integer
      - name: toolID
        in: path
        required: true
        schema:
          type: string
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - seed
      summary: Get a specific seed by ID
      operationId: getSeedById
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seed"

    put:
      tags:
        - seed
      summary: Update a specific seed by ID
      operationId: updateSeedById
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Seed"
      responses:
        '200':
          description: Successful update
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Seed"

    delete:
      tags:
        - seed
      summary: Delete a specific seed by ID
      operationId: deleteSeedById
      responses:
        '204':
          description: Deleted Successfully

components:
  schemas:
    Seed:
      type: object
      x-class-extra-annotation: |-
        @jakarta.persistence.Entity
        @jakarta.persistence.Table(
            name = "seed"
          )
      properties:
        id:
          type: integer
          x-field-extra-annotation: |-
            @jakarta.persistence.Id
            @jakarta.persistence.GeneratedValue(strategy = jakarta.persistence.GenerationType.IDENTITY)
          description: Autogenerated primary key
          x-id-attribute: true
        createdBy:
          type: integer
        createdAt:
          type: string
          format: date-time
        updatedBy:
          type: integer
        updatedAt:
          type: string
          format: date-time
        createdByToolId:
          type: string
        updatedByToolId:
          type: string
        title:
          type: string
        cropId:
          type: integer
        name:
          type: string
        description:
          type: string
        imageId:
          type: integer
        variety:
          type: string
        varietyType:
          type: integer
        famousFor:
          type: string
        sowingTime:
          type: string
        sowingMethod:
          type: string
        plantRowDistance:
          type: string
        immunity:
          type: string
        seedTreatmentMethods:
          type: string
        cropDuration:
          type: integer
        firstHarvesting:
          type: integer
        produceShape:
          type: string
        produceColor:
          type: string
        produceSize:
          type: string
        produceTaste:
          type: string
        urlStr:
          type: string
        perAcreRequirementMin:
          type: integer
        perAcreRequirementMax:
          type: integer
        perAcreCostMin:
          type: integer
        perAcreCostMax:
          type: integer
        is_deleted:
          type: boolean
          default: false
      required:
        - name
        - cropId
