CREATE TABLE IF NOT EXISTS public.eppo_codes
(
    id SERIAL PRIMARY KEY ,
    authority character varying(60) ,
    code character varying(8) ,
    country character varying(2) ,
    datatype character varying(3) ,
    full_name character varying(60) ,
    identifier character varying(10) ,
    lang_no character varying(2) ,
    language character varying(2) ,
    short_name character varying(30) ,
    created_at timestamp(6) without time zone,
    created_by integer ,
    created_by_tool_id character varying(255) ,
    realm_id character varying(255) ,
    updated_at timestamp(6) without time zone,
    updated_by integer ,
    updated_by_tool_id character varying(255),
    is_deleted boolean default false
    );
CREATE TABLE IF NOT EXISTS public.unspsc_codes (
    id SERIAL PRIMARY KEY,
    realm_id character varying(255),
    created_by integer,
    created_at TIMESTAMP,
    updated_by integer,
    updated_at TIMESTAMP,
    created_by_tool_id character varying(255),
    updated_by_tool_id character varying(255),
    segment integer,
    segment_name character varying(255),
    family integer,
    family_name character varying(255),
    class_code integer,
    class_name character varying(255),
    commodity integer,
    commodity_name character varying(255),
    is_deleted boolean default false
    );

CREATE TABLE IF NOT EXISTS public.agristack_crop (
    id SERIAL PRIMARY KEY,
    realm_id character varying(255),
    created_by integer,
    created_at timestamp(6) without time zone,
    updated_by integer,
    updated_at timestamp(6) without time zone,
    created_by_tool_id character varying(255),
    updated_by_tool_id character varying(255),
    crop_registry_entity_identifier_crop_code integer,
    crop_name character varying(255),
    crop_type character varying(255),
    scientific_name_of_crop character varying(255),
    crop_category character varying(255),
    hindi_name_of_crop character varying(255),
    vernacular_name_of_crop_in_english_by_assam character varying(255),
    is_deleted boolean default false
    );
CREATE TABLE IF NOT EXISTS  public.crop_details (
    id integer NOT NULL,
    realm_id character varying(255),
    created_by integer,
    created_at timestamp without time zone,
    updated_by integer,
    updated_at timestamp without time zone,
    created_by_tool_id character varying(255),
    updated_by_tool_id character varying(255),
    crop_id integer,
    lang_id integer,
    eppocode integer ,
    unspsc integer,
    author_id integer,
    time timestamp without time zone,
    name text,
    description text,
    diseases text,
    farming_regions text,
    fertilizers text,
    income text,
    input_cost text,
    irrigation_methods text,
    machines_required text,
    market_demand text,
    revenue text,
    seed_procurement text,
    seed_quantity text,
    seed_types text,
    soil_preparation text,
    sowing_method text,
    weed_management text,
    nutritional_details text,
    published boolean default false not null,
    version_id integer,
    parent_id integer,
    is_approved smallint,
    reviewer_remarks text,
    last_updated_at timestamp without time zone,
    approved_at timestamp without time zone,
    approved_by integer,
    FOREIGN KEY (eppocode) REFERENCES eppo_codes(id),
    FOREIGN KEY (unspsc) REFERENCES unspsc_codes(id)
);
CREATE TABLE IF NOT EXISTS public.event_publication
(
    id uuid NOT NULL,
    completion_date timestamp(6) with time zone,
    event_type character varying(255) ,
    listener_id character varying(255) ,
    publication_date timestamp(6) with time zone,
    serialized_event character varying(255) ,
    is_deleted boolean default false ,
    CONSTRAINT event_publication_pkey PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS public.crop
(
    id SERIAL PRIMARY KEY ,
    alternate_name character varying(255) ,
    realm_id character varying(255),
    eppocode integer ,
    unspsc integer,
    created_at timestamp(6) without time zone,
    created_by integer ,
    created_by_tool_id character varying(255) ,
    crop_icon_image character varying(255) ,
    crop_image character varying(255) ,
    crop_type_id integer,
    description character varying(255) ,
    diseases character varying(255) ,
    external_hash_id character varying(255) ,
    farming_regions character varying(255) ,
    fertilizers character varying(255) ,
    hash_id character varying(255) ,
    hindi_name character varying(255) ,
    income character varying(255) ,
    input_cost character varying(255) ,
    irrigation_methods character varying(255) ,
    machines_required character varying(255) ,
    market_demand character varying(255) ,
    name character varying(255) ,
    nutritional_details character varying(255) ,
    reaping_end_time smallint,
    reaping_start_time smallint,
    revenue character varying(255) ,
    season smallint,
    seed_procurement character varying(255) ,
    seed_quantity character varying(255) ,
    seed_types character varying(255) ,
    segment_id integer,
    soil_preparation character varying(255) ,
    sowing_end_time smallint,
    sowing_method character varying(255) ,
    sowing_reaping_time character varying(255) ,
    sowing_start_time smallint,
    updated_at timestamp(6) without time zone,
    updated_by integer ,
    updated_by_tool_id character varying(255) ,
    url_str character varying(255) ,
    version_id integer,
    weed_management character varying(255),
    is_deleted boolean default false ,
    FOREIGN KEY (eppocode) REFERENCES eppo_codes(id),
    FOREIGN KEY (unspsc) REFERENCES unspsc_codes(id)
    );

CREATE TABLE IF NOT EXISTS public.fertilizer
(
    id SERIAL PRIMARY KEY ,
    name character varying(200) ,
    created_at timestamp(6) without time zone,
    created_by integer ,
    created_by_tool_id character varying(255) ,
    updated_at timestamp(6) without time zone,
    updated_by integer ,
    updated_by_tool_id character varying(255) ,
    realm_id character varying(255) ,
    is_deleted boolean default false
    );

CREATE TABLE IF NOT EXISTS public.pesticide
(
    id SERIAL PRIMARY KEY ,
    application_frequency character varying(255) ,
    application_method character varying(255) ,
    benefits character varying(255) ,
    brand character varying(255) ,
    chemical_composition character varying(255) ,
    compatibility character varying(255) ,
    cost_of_single_dosage integer,
    dosage_per_acre character varying(255) ,
    dosage_per_litre character varying(255) ,
    effect_duration character varying(255) ,
    extra_description character varying(255) ,
    form character varying(255) ,
    hash_id character varying(255) ,
    img1 character varying(255) ,
    name character varying(255) ,
    pesticide_type character varying(255) ,
    pesticide_type_id integer,
    price integer,
    quantity character varying(255) ,
    special_remarks character varying(255) ,
    spectrum character varying(255) ,
    url_str character varying(255) ,
    version_id integer,
    created_at timestamp(6) without time zone,
    created_by integer ,
    created_by_tool_id character varying(255) ,
    updated_at timestamp(6) without time zone,
    updated_by integer ,
    updated_by_tool_id character varying(255) ,
    realm_id character varying(255) ,
    is_deleted boolean default false
    );

CREATE TABLE IF NOT EXISTS public.seed
(
    id SERIAL PRIMARY KEY ,
    crop_duration integer,
    crop_id integer,
    description character varying(255),
    famous_for character varying(255),
    first_harvesting integer,
    image_id integer,
    immunity character varying(255),
    name character varying(255),
    per_acre_cost_max integer,
    per_acre_cost_min integer,
    per_acre_requirement_max integer,
    per_acre_requirement_min integer,
    plant_row_distance character varying(255),
    produce_color character varying(255),
    produce_shape character varying(255),
    produce_size character varying(255),
    produce_taste character varying(255),
    seed_treatment_methods character varying(255),
    sowing_method character varying(255),
    sowing_time character varying(255),
    title character varying(255),
    url_str character varying(255),
    variety character varying(255),
    variety_type integer,
    created_at timestamp(6) without time zone,
    created_by integer,
    created_by_tool_id character varying(255),
    updated_at timestamp(6) without time zone,
    updated_by integer,
    updated_by_tool_id character varying(255),
    realm_id character varying(255) ,
    is_deleted boolean default false
    )



